development:
  adapter: postgresql
  encoding: unicode
  database: development
  host: localhost
  template: template0
  pool: 5
  username: nicholas
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: test
  host: localhost
  template: template0
  pool: 5
  username: nicholas
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: production
  host: localhost
  template: template0
  pool: 5
  username: nicholas
  password:
